CREATE TABLE clients (
    id BIGSERIAL PRIMARY KEY,
    unique_id VARCHAR(256) NOT NULL UNIQUE,
    client_id VARCHAR(256) NOT NULL UNIQUE,
    client_secret VARCHAR(256) NOT NULL,
    redirect_uri VARCHAR(256) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
);
